language: common-lisp
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - CXX=clang++

install:
  - sudo apt-get install -y pkg-config libltdl3-dev libhwloc-dev llvm-dev clang libclang-dev ocl-icd-opencl-dev libedit-dev

  - pwd
  - pushd .
  - pwd
  - cd $HOME
  - wget http://portablecl.org/downloads/pocl-0.12.tar.gz
  - tar xzf pocl-0.12.tar.gz && cd pocl-0.12/ && ./configure && make && sudo make install
  - popd
  - pwd
  - wget https://github.com/clMathLibraries/clBLAS/archive/v2.10.zip
  - unzip v2.10.zip && pushd clBLAS-2.10/src && cmake . && make && sudo make install && popd

cache:
  directories:
    - $HOME/pocl-0.12

script:
  - pwd
  - cd
  - pwd
